# Generated by Django 4.2.6 on 2023-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcards', '0003_card_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='condition',
            field=models.CharField(choices=[('Mint', 'Mint'), ('Excellent', 'Excellent'), ('Great', 'Great'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=10),
        ),
    ]
