# Generated by Django 4.2.6 on 2023-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcards', '0004_alter_card_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='condition',
            field=models.CharField(choices=[('Mint', 'Mint'), ('Excellent', 'Excellent'), ('Great', 'Great'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], db_index=True, default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='team',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
